// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TypeSqlx {
    #[prost(oneof = "type_sqlx::Types", tags = "1, 2, 3, 4, 5, 6")]
    pub types: ::core::option::Option<type_sqlx::Types>,
}
/// Nested message and enum types in `TypeSqlx`.
pub mod type_sqlx {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Types {
        #[prost(message, tag = "1")]
        S(super::Varchar),
        #[prost(message, tag = "2")]
        I(super::Bigint),
        #[prost(message, tag = "3")]
        N(super::Numeric),
        #[prost(message, tag = "4")]
        D(super::Date),
        #[prost(message, tag = "5")]
        T(super::Time),
        #[prost(message, tag = "6")]
        V(super::Void),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Varchar {
    #[prost(string, tag = "1")]
    pub value: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Bigint {
    #[prost(int64, tag = "1")]
    pub value: i64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Numeric {
    #[prost(double, tag = "1")]
    pub value: f64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Date {
    #[prost(message, optional, tag = "1")]
    pub value: ::core::option::Option<NaiveDate>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Time {
    #[prost(message, optional, tag = "1")]
    pub value: ::core::option::Option<NaiveTime>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Void {
    #[prost(message, optional, tag = "1")]
    pub value: ::core::option::Option<VoidStruct>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Bool {
    #[prost(bool, tag = "1")]
    pub value: bool,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct NaiveDate {
    #[prost(int32, tag = "1")]
    pub year: i32,
    #[prost(int32, tag = "2")]
    pub month: i32,
    #[prost(int32, tag = "3")]
    pub day: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct NaiveTime {
    #[prost(int32, tag = "1")]
    pub hour: i32,
    #[prost(int32, tag = "2")]
    pub minute: i32,
    #[prost(int32, tag = "3")]
    pub second: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct VoidStruct {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RowOfDb {
    #[prost(message, repeated, tag = "1")]
    pub cols: ::prost::alloc::vec::Vec<TypeSqlx>,
    #[prost(string, repeated, tag = "2")]
    pub cols_name: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
